Repository w3c/process, pull requests merged in 2019-02, with the labels that each got.

#237 Spelling fixes and one typo fix.
  index.html
Labels: Type: editorial improvements

#248 Drop redundant word
  index.bs
Labels: Agenda+, DoC, Type: editorial improvements

#252 Fix incorrect punctuation
  index.bs
Labels: DoC, Type: editorial improvements

#240 [editorial] Grammar fix: add missing auxiliary
  index.bs
Labels: DoC, Type: editorial improvements

#247 Remove extraneous phrasing
  index.bs
Labels: Agenda+, DoC, Type: editorial improvements
