Repository w3c/process, pull requests merged in 2020-03, with the labels that each got.

#387 Typo correction; plural 'seats' in 2.5.3
  index.bs
Labels: DoC, Type: editorial improvements

#384 description for "The Art of Consensus"
  index.bs
Labels: Closed: Accepted, DoC, Type: editorial improvements

#383 Use actual title of the linked document
  index.bs
Labels: Type: editorial improvements

#369 hyphen
  index.bs
Labels: Type: editorial improvements

#370 removed spurious period mid-sentence
  index.bs
Labels: Type: editorial improvements

#372 Update link that redirected
  index.bs
Labels: Type: editorial improvements

#374 link to ML archive rather than ML mailto
  index.bs
Labels: Closed: Accepted, DoC, Type: editorial improvements

#375 typo
  index.bs
Labels: Type: editorial improvements

#377 typo
  index.bs
Labels: Type: editorial improvements

#378 Fixed letter case
  index.bs
Labels: Type: editorial improvements

#379 number (editorial)
  index.bs
Labels: Type: editorial improvements

#380 punctuation
  index.bs
Labels: DoC, Type: editorial improvements

#381 order of actions
  index.bs
Labels: Type: editorial improvements

#382 Moar re-ordering
  index.bs
Labels: Type: editorial improvements

#357 spelling fix: judgment
  index.bs
Labels: DoC, Type: editorial improvements
