Repository w3c/process, pull requests merged in 2020-08, with the labels that each got.

#376 Editorial pass
  index.bs
Labels: Closed: Accepted, Type: editorial improvements

#430 Fix terminology mixup
  index.bs
Labels: Closed: Accepted, Type: editorial improvements

#431 User consistent terminology (short vs incomplete terms)
  index.bs
Labels: Closed: Accepted, Type: editorial improvements

#254 [director-free] Gratuitous mentions of the Director
  index.bs
Labels: Closed: Accepted, P2021: Priority, d-f: general

#444 Editorial tweak in Superseded Recommendation note
  index.bs
Labels: Type: editorial improvements
