Repository w3c/process, pull requests merged in 2021-09, with the labels that each got.

#562 Make it possible to transition from REC to WD
  index.bs
Labels: Closed: Accepted

#563 Stop excluding AC rep comments from those that have to be addressed
  index.bs
Labels: Closed: Accepted

#567 Use "allow new features" terminology consistently
  index.bs
Labels: Type: Editorial improvements, Closed: Accepted

#571 Require document license to go through formal approval for updates
  index.bs
Labels: AC-review, Closed: Accepted
