Repository w3c/process, pull requests merged in 2021-05, with the labels that each got.

#526 Acknowledge existence of public channels for charter comments
  index.bs
Labels: Agenda+

#519 Generalize where decisions can be made
  index.bs
Labels: Agenda+

#524 Alternate AC Rep
  index.bs
Labels: Agenda+

#530 Rename "Other Charter"
  index.bs
Labels: Agenda+

#520 Rewrite the introduction
  index.bs
Labels: Agenda+, P2021 final cleanup

#534 Improve the wording on normative requirements related to registry values
  index.bs
Labels: Agenda+, P2021 final cleanup

#533 Provide facilities for the Team to maintain orphaned Notes
  index.bs
Labels: Closed: Accepted

#531 45-day rejoin window
  index.bs
Labels: P2021 final cleanup
