Repository w3c/process, pull requests merged in 2022-08, with the labels that each got.

#612 Rename "maturity level" into "maturity stage"
  index.bs
Labels: Type: Editorial improvements, Agenda+

#614 editorial: rm undefined COO from informal Note
  index.bs
Labels: Type: Editorial improvements, Closed: Accepted

#619 Provide an explicit advance notice period for MoUs
  index.bs
Labels: Agenda+, Closed: Accepted
