Repository w3c/process, pull requests merged in 2022-10, with the labels that each got.

#635 Improving the definition of consensus
  index.bs
Labels: Agenda+

#642 Adopt the W3C Council for handing Formal objections and related matters
  index.bs
Labels: Agenda+, Director-free: FO/Council, Director-free (all)

#647 Define editorial vs substantive changes for non-REC-track documents.
  index.bs
Labels: Agenda+, Director-free (all)

#654 Define CRS/CRD abbreviations, fixes #636
  basic-rec-track.svg
  index.bs
Labels: Type: Editorial improvements

#664 Allow the CEO to delegate their seat on the Council
  index.bs
Labels: Closed: Accepted, Director-free: FO/Council, Director-free (all)

#646 Replace the role of the Director in concluding AC Review
  index.bs
Labels: Closed: Accepted, Director-free (all)

#659 Clarify expectations about FO mitigations
  index.bs
Labels: Type: Editorial improvements

#658 Remove references to the Hosts, replace with BoD
  index.bs
Labels: Closed: Accepted

#665 The council may report vote totals
  index.bs
Labels: Agenda+, Director-free: FO/Council, Director-free (all)
