Repository w3c/process, pull requests merged in 2024-12, with the labels that each got.

#960 Fix links
  index.bs
Labels: Type: Editorial improvements

#961 Fix links (2nd batch)
  index.bs
Labels: Type: Editorial improvements, Closed: Accepted

#954 Introduce Good Standing
  index.bs
Labels: Closed: Accepted

#953 Require documentation of how FOs get resolved
  index.bs
Labels: Closed: Accepted

#952 Defer to /Guide for specific mailing lists to send review requests to
  index.bs
Labels: Closed: Accepted

#950 Allow for some amount of leeway at the close of nomination periods
  index.bs
Labels: Closed: Accepted
