Repository w3c/process, pull requests merged in 2025-03, with the labels that each got.

#995 Require Team to reply with rationale for rejection
  index.bs
Labels: Closed: Accepted

#994 Pick a number of weeks
  index.bs
Labels: Closed: Accepted

#988 Improve markup/typography
  index.bs
Labels: Type: Editorial improvements, Closed: Accepted

#1002 Facilitator not explicitly chair
  index.bs
Labels: Closed: Accepted, topic: Chartering

#1005 Reframe the various kinds of Objection handling for charter refinement
  index.bs
Labels: Closed: Accepted, topic: Chartering

#986 Enable AB/TAG to remove one of their members
  index.bs
Labels: Closed: Accepted

#1016 (Editorial) Typo fix
  index.bs
Labels: Type: Editorial improvements, Closed: Accepted
