Repository w3c/process, pull requests merged in 2025-06, with the labels that each got.

#1065 Remove a stray emdash.
  index.bs
Labels: Type: Editorial improvements, Closed: Accepted

#1067 Drop legacy aliases for Group Note from the definition
  index.bs
  snapshots/2025-05.html
Labels: Type: Editorial improvements, Closed: Accepted

#1068 Rename "Team Contact" into "Staff Contact"
  index.bs
Labels: Type: Editorial improvements, Closed: Accepted

#1046 Clarify timing of Council being convened
  index.bs
Labels: Closed: Accepted

#1045 Clarify council text in case of multiple objections to a single decision
  index.bs
Labels: Closed: Accepted

#1069 Explain the reasons for the Council confidentiality requirements
  index.bs
Labels: Closed: Accepted

#1072 Correct council text pertaining to multiple objections / decisions
  index.bs
Labels: Agenda+, Director-free: FO/Council
