Repository w3c/process, pull requests merged in 2025-04, with the labels that each got.

#1015 chore: replace informative with non-normative for consistency
  index.bs
Labels: Agenda+

#1010 Make cross reference more obvious
  index.bs
Labels: Agenda+

#1023 Notify the AC when an AB or TAG member is removed.
  index.bs
Labels: Agenda+

#1027 Removal hearings are held by the group, not the chair.
  index.bs
Labels: Agenda+

#1026 Fix confusing wording wrt adding new features to RECs #1004
  index.bs
Labels: Closed: Accepted

#1000 Move details of how the Team evaluates charters to the guide
  index.bs
Labels: Closed: Accepted, topic: Chartering

#1011 Refine Expiration of Charter Refinement
  index.bs
Labels: Closed: Accepted, topic: Chartering
