Repository w3c/process, pull requests merged in 2025-01, with the labels that each got.

#964 Decrease emphasis on FO to charter rejection
  index.bs
Labels: Agenda+

#970 Enable the Team (as well as the Group) to push charters forward
  index.bs
Labels: Closed: Accepted, topic: Chartering

#955 Be more specific about when the council composition is locked down
  index.bs
Labels: Agenda+

#973 Add explicit Team verification of charter refinement
  index.bs
Labels: Closed: Accepted

#975 Call out that the Team can share its views on proposals under AC review
  index.bs
Labels: Closed: Accepted

#792 Limit the involvement of Tim Berners-Lee to the TAG proper
  index.bs
Labels: Agenda+, Director-free: FO/Council, Director-free (all), P2025 candidate

#979 Update links to the Guidebook following its redesign
  index.bs
Labels: Type: Editorial improvements, Closed: Accepted

#972 Extend the ability to publish Registries to IG/AB/TAG
  index.bs
Labels: Agenda+
